version: "3.9"
services:
  app:
    image: 'user-transactions:1.0'
    ports:
      - "8080:8080"
    depends_on: [
      postgres
    ]
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432